"""Initial migration

Revision ID: 31abd2e1e4ca
Revises: 
Create Date: 2026-02-25 01:09:13.982470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31abd2e1e4ca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ruc', sa.String(length=11), nullable=False),
    sa.Column('razon_social', sa.String(length=255), nullable=False),
    sa.Column('nombre_comercial', sa.String(length=255), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('ubigeo', sa.String(length=6), nullable=True),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.Column('provincia', sa.String(length=100), nullable=True),
    sa.Column('distrito', sa.String(length=100), nullable=True),
    sa.Column('sol_user', sa.Text(), nullable=True),
    sa.Column('sol_password', sa.Text(), nullable=True),
    sa.Column('certificate', sa.LargeBinary(), nullable=True),
    sa.Column('certificate_password', sa.Text(), nullable=True),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('send_email', sa.Boolean(), nullable=False),
    sa.Column('generate_pdf', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ruc')
    )
    op.create_index(op.f('ix_clients_api_key_hash'), 'clients', ['api_key_hash'], unique=True)
    op.create_table('document_series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(length=2), nullable=False),
    sa.Column('series', sa.String(length=4), nullable=False),
    sa.Column('current_correlative', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'series', name='uq_client_series')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(length=2), nullable=False),
    sa.Column('series', sa.String(length=4), nullable=False),
    sa.Column('correlative', sa.Integer(), nullable=False),
    sa.Column('customer_doc_type', sa.String(length=1), nullable=False),
    sa.Column('customer_doc_number', sa.String(length=20), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_address', sa.String(length=255), nullable=True),
    sa.Column('issue_date', sa.DateTime(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('total_gravada', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_igv', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('xml_content', sa.Text(), nullable=True),
    sa.Column('xml_signed', sa.Text(), nullable=True),
    sa.Column('cdr_content', sa.Text(), nullable=True),
    sa.Column('cdr_code', sa.String(length=10), nullable=True),
    sa.Column('cdr_description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=10), nullable=False),
    sa.Column('unit_code', sa.String(length=5), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=10), nullable=False),
    sa.Column('igv_type', sa.String(length=2), nullable=False),
    sa.Column('igv', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_items')
    op.drop_table('documents')
    op.drop_table('document_series')
    op.drop_index(op.f('ix_clients_api_key_hash'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
