"""add_serie_fields_and_fix_constraint

Revision ID: 8c7d2d1a8ac3
Revises: c73e3e443106
Create Date: 2026-02-28 23:14:35.909100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c7d2d1a8ac3'
down_revision: Union[str, None] = 'c73e3e443106'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('serie_factura', sa.String(length=4), nullable=True))
    op.add_column('clients', sa.Column('serie_boleta', sa.String(length=4), nullable=True))
    op.drop_constraint('uq_client_series', 'document_series', type_='unique')
    op.create_unique_constraint('uq_client_doc_type_series', 'document_series', ['client_id', 'document_type', 'series'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_client_doc_type_series', 'document_series', type_='unique')
    op.create_unique_constraint('uq_client_series', 'document_series', ['client_id', 'series'])
    op.drop_column('clients', 'serie_boleta')
    op.drop_column('clients', 'serie_factura')
    # ### end Alembic commands ###
