"""fix_quantity_unit_price_precision

Revision ID: c73e3e443106
Revises: 31abd2e1e4ca
Create Date: 2026-02-25 03:14:42.832098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c73e3e443106'
down_revision: Union[str, None] = '31abd2e1e4ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'distrito')
    op.drop_column('clients', 'departamento')
    op.drop_column('clients', 'provincia')
    op.alter_column('document_items', 'quantity',
               existing_type=sa.NUMERIC(precision=12, scale=10),
               type_=sa.Numeric(precision=14, scale=4),
               existing_nullable=False)
    op.alter_column('document_items', 'unit_price',
               existing_type=sa.NUMERIC(precision=12, scale=10),
               type_=sa.Numeric(precision=14, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_items', 'unit_price',
               existing_type=sa.Numeric(precision=14, scale=4),
               type_=sa.NUMERIC(precision=12, scale=10),
               existing_nullable=False)
    op.alter_column('document_items', 'quantity',
               existing_type=sa.Numeric(precision=14, scale=4),
               type_=sa.NUMERIC(precision=12, scale=10),
               existing_nullable=False)
    op.add_column('clients', sa.Column('provincia', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('departamento', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('distrito', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
